# Generated by Django 4.2.4 on 2023-09-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "restaurant",
            "0003_remove_booking_comment_remove_booking_guest_number_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="reservation_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
