# Generated by Django 4.2.4 on 2023-09-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0004_alter_booking_reservation_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menu",
            old_name="menu_item_description",
            new_name="description",
        ),
        migrations.AlterField(
            model_name="menu",
            name="price",
            field=models.FloatField(),
        ),
    ]
